/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package dk.napp.uagcm;

import java.util.ArrayList;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollFunction;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import android.app.Activity;
import android.app.NotificationManager;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Bundle;

//UA
import com.urbanairship.AirshipConfigOptions;
import com.urbanairship.Logger;
import com.urbanairship.UAirship;
import com.urbanairship.location.UALocationManager;
import com.urbanairship.push.PushManager;
import com.urbanairship.push.PushPreferences;


@Kroll.module(name="Nappuagcm", id="dk.napp.uagcm")
public class NappuagcmModule extends KrollModule
{

	// Standard Debugging variables
	private static final String LCAT = "Napp-UA-GCM";
	private static final boolean DBG = TiConfig.LOGD;
	
	private static NappuagcmModule _THIS;
	
	private KrollFunction successCallback;
    private KrollFunction errorCallback;
    private KrollFunction messageCallback;

    private AirshipConfigOptions airshipConfig;
    
    private String mActivityName;
    private String mPackageName;
    private ArrayList<Bundle> mMessageList;
    
    IntentFilter boundServiceFilter;


	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public NappuagcmModule()
	{
		super();
		_THIS = this;
		
		airshipConfig = null;
        mActivityName = null;
        mPackageName = null;
        
        successCallback = null;
        errorCallback = null;
        messageCallback = null;

        mMessageList = new ArrayList<Bundle>();
        
        //location
        boundServiceFilter = new IntentFilter();
        boundServiceFilter.addAction(UALocationManager.getLocationIntentAction(UALocationManager.ACTION_SUFFIX_LOCATION_SERVICE_BOUND));
        boundServiceFilter.addAction(UALocationManager.getLocationIntentAction(UALocationManager.ACTION_SUFFIX_LOCATION_SERVICE_UNBOUND));

	}
	
	static NappuagcmModule getInstance() {
        return _THIS;
    }

	public void onResume(Activity activity) {
    	Log.i(LCAT, "onResume: ");
    	Intent intent = activity.getIntent();
    	ArrayList messages = intent.getParcelableArrayListExtra("messages");
    	if(messages!=null) {
    		mMessageList.addAll(messages);
    	}
    	Bundle opened = intent.getBundleExtra("opened");

    	Log.i(LCAT, "total messages: "+mMessageList.size());
		if(messages!=null) {
    		Log.i(LCAT, "received messages: "+messages.size());
    	}
    	if(opened!=null) {
    		Log.i(LCAT, "received opened: "+opened.getString(PushManager.EXTRA_ALERT));	
    	}
    	pushMessage();
	}
	
	
	public void clearNotifications() {    	
    	// Clear all of notification messages.
    	//String ns = getTiContext().getTiApp().NOTIFICATION_SERVICE;
    	String ns = getActivity().NOTIFICATION_SERVICE;
    	
		NotificationManager mNotificationManager = (NotificationManager) getActivity().getSystemService(ns);
		mNotificationManager.cancelAll();
    }
	
	public void registerCallback(boolean valid, String apid) {
		KrollDict dict = new KrollDict();		
		dict.put("apid", apid);
		dict.put("success", valid);

    	//Activity myAct = getTiContext().getTiApp().getCurrentActivity();
    	Activity myAct = getActivity();
		if (valid) {
			if(myAct!=null && successCallback!=null) {
				successCallback.callAsync(getKrollObject(), dict);
			}
		} else {
			if(myAct!=null && errorCallback!=null) {
				errorCallback.callAsync(getKrollObject(), dict);
			}
		}
	}
	
    private void pushMessage() {
    	Log.i(LCAT, "Push message: " + mMessageList.size());
    	//Activity myAct = getTiContext().getTiApp().getCurrentActivity();
    	Activity myAct = getActivity();
    	if(myAct != null) {
    		// Make KrollDict value
    		int size = mMessageList.size();
    		KrollDict dict = new KrollDict();
    		for (int i=0; i<size; i++) {
    			Bundle bundle = mMessageList.get(i);
    			int id = bundle.getInt(PushManager.EXTRA_NOTIFICATION_ID);
    			String alert = bundle.getString(PushManager.EXTRA_ALERT);
    			Log.i(LCAT, "message["+id+"] "+alert);
    			dict.put(Integer.toString(id), alert);
    		}
    		if(size>0 && messageCallback != null) {
    			messageCallback.callAsync(getKrollObject(), dict);
			}
    		mMessageList.clear();
	    	clearNotifications();
    	}
    }
    
    public void sendMessage(Bundle bundle) {
    	Log.i(LCAT, "Message from intent receiver.");
    	
    	// Put message to list
    	mMessageList.add(bundle);
    	
    	// Push message
		pushMessage();
    }

    private AirshipConfigOptions getAirshipConfig() {
        return airshipConfig;
    }
    
    private void registerUA() {
		Log.d(LCAT, "inside registerUA()");
		
		
        //UAirship.takeOff(getTiContext().getTiApp(), getAirshipConfig());
		UAirship.takeOff(TiApplication.getInstance(), getAirshipConfig());

        PushManager.enablePush();

		PushPreferences prefs = PushManager.shared().getPreferences();
		Logger.info("My Application onCreate - App APID: " + prefs.getPushId());

        // Set intent receiver
        PushManager.shared().setIntentReceiver(IntentReceiver.class);
    }

    public String getPackageName() {
    	return mPackageName;
    }

    public String getActivityName() {
    	return mActivityName;
    }
    
    public ArrayList getMessageList() {
    	return mMessageList;
    }

    @Kroll.method
    public void setAirshipConfig(KrollDict param){
        AirshipConfigOptions options = new AirshipConfigOptions();

        options.inProduction = (Boolean)param.get("inProduction");
        options.pushServiceEnabled = (Boolean)param.get("pushServiceEnabled");
        options.gcmSender = (String)param.get("gcmSender");
        options.transport = (String)param.get("transport");
        options.productionAppKey = (String)param.get("productionAppKey");
        options.productionAppSecret = (String)param.get("productionAppSecret");
        options.developmentAppKey = (String)param.get("developmentAppKey");
        options.developmentAppSecret = (String)param.get("developmentAppSecret");

        airshipConfig = options;
    }

	@Kroll.method
	public String getApid() {
		return PushManager.shared().getAPID();
	}
	
	@Kroll.method
    public void registerForPushNotifications(KrollDict param) {
		Log.d(LCAT, "inside registerForPushNotifications()");

        Activity myAct = getActivity();
        mPackageName = myAct.getComponentName().getPackageName();
        mActivityName = myAct.getComponentName().getClassName();

		successCallback = (KrollFunction) param.get("success");
        errorCallback = (KrollFunction) param.get("error");
        messageCallback = (KrollFunction) param.get("callback");
        
        Log.d(LCAT, "package name: " + mPackageName);
		Log.d(LCAT, "activity name: " + mActivityName);

        setAirshipConfig(param);

        registerUA();
    }
	
	@Kroll.method
    public void enableLocation(KrollDict param) {
		Log.d(LCAT, "inside enableLocation()");
		
		boolean isLocationEnabledInActivity = param.optBoolean("location", false);
        boolean isBackgroundLocationEnabledInActivity = param.optBoolean("backgroundLocation", false);

        if (isLocationEnabledInActivity) {
            UALocationManager.enableLocation();
            if (isBackgroundLocationEnabledInActivity) {
                UALocationManager.enableBackgroundLocation();
            } else {
                UALocationManager.disableBackgroundLocation();
            }
        } else {
        	if (isBackgroundLocationEnabledInActivity) {
                UALocationManager.enableBackgroundLocation();
            } else {
                UALocationManager.disableBackgroundLocation();
            }
            UALocationManager.disableLocation();
        }	
	}
	
	
	private BroadcastReceiver boundServiceReceiver = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
        	UALocationManager.getLocationIntentAction(UALocationManager.ACTION_SUFFIX_LOCATION_SERVICE_BOUND);
        }
    };


}

